model:
  optimizer: Adam
  epochs:  1000
  save_every: -1
  lr: 0.0001
  # -  lr_decay_rate: 0.9
  seed: 594277
  bn_momentum: 0
  freeze_earlier_blocks: -1
  beta1: 0.9
  weight_decay: 0.0
  num_workers: 4
  batch_size: 16